### ISSUE TITLE
jquery 2.2.1 breaks webpack builds when loading individual modules

### ISSUE THREAD

**Issue by bertez** [jquery/jquery#2945]
Hi,

after this change https://github.com/jquery/jquery/commit/5943f1d7ffef41cc1a99bffe189f6d111fbccfd0 webpack builds are broken when loading individual modules:

`ERROR in ./~/jquery/src/selector-sizzle.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../external/sizzle/dist/sizzle in /Users/berto/Temp/webpack-jquery/node_modules/jquery/src
 @ ./~/jquery/src/selector-sizzle.js 1:0-14:3`

I think this is happening because in 2.2.1 'selector-sizzle.js' is trying to load the sizzle dependency as '../external/sizzle/dist/sizzle' a file which does not exist, unlike in 2.2.0 (for instance) which loads 'sizzle'.

I set up a simple example here: https://github.com/bertez/webpack-jquery
```
npm install
npm run build
```
Thank you very much in advance.

**Comment by hccampos** [comment]
Indeed, experiencing the same thing here. Should be possible to add some alias to the config to fix it, but would indeed be much better if jquery just loaded 'sizzle' so that webpack can fetch it from the node_modules folder or wherever it is resolving from.

**Comment by mgol** [comment]
It seems we should include `external/sizzle` in the published package. Could you check if it starts working if you copy this directory from the jQuery repo to `node_modules/jquery/external/sizzle/`?

**Comment by timmywil** [comment]
yup, `external/sizzle` should have been included. We could actually fix this in npm for 1.12.1/2.2.1.

**Comment by timmywil** [comment]
We'll include this fix in 1.12.2/2.2.2.

**Comment by timmywil** [comment]
Fixed by ed94387, 5d620be, and 8a91f84.

**Comment by bertez** [comment]
Thank you!

**Comment by phkavitha** [comment]
What's the fix for this? I find that the version 1.12.2 and 2.2.2 is still not available in CDN (https://code.jquery.com/jquery/).

**Comment by bertez** [comment]
2.2.0 is working for me...

**Comment by mgol** [comment]
We'll discuss it on Monday. We might need to fix more things and we don't want to release every few days.

**Comment by phkavitha** [comment]
Thanks @bertez . It worked for me. I used jquery v2.2.0 and sizzle v2.3.0.

**Comment by musicformellons** [comment]
mmh, just installed 1.12.3 and still got this error; after adding an external folder etc it worked.

**Comment by codahale** [comment]
This doesn’t appear to be fixed. I’m getting this error w/ 2.2.2 and 2.2.3:

```
ERROR in ../~/jquery/src/selector-sizzle.js
Module not found: Error: Can't resolve '../external/sizzle/dist/sizzle' in '/Users/coda/Projects/example/node_modules/jquery/src'
 @ ../~/jquery/src/selector-sizzle.js 1:13-313
```

The reference is to `../external/sizzle/dist/sizzle`, but no directory named `external` exists in `node_modules/jquery`:

```
$ tree node_modules/jquery/
node_modules/jquery/
├── AUTHORS.txt
├── LICENSE.txt
├── README.md
├── bower.json
├── dist
│   ├── jquery.js
│   ├── jquery.min.js
│   ├── jquery.min.map
│   ├── jquery.slim.js
│   ├── jquery.slim.min.js
│   └── jquery.slim.min.map
├── package.json
├── sizzle
│   ├── LICENSE.txt
│   └── dist
│       ├── sizzle.js
│       ├── sizzle.min.js
│       └── sizzle.min.map
└── src
    ├── ajax
    │   ├── jsonp.js
etc. etc.
```

**Comment by mgol** [comment]
Yeah, this was not fixed correctly. Everything from [the `extras` array](https://github.com/jquery/jquery/blob/e8825a529b97a27b8b2e40eaaa7773189642c772/build/release/dist.js#L13-L19) is copied directly to [the final directory](https://github.com/jquery/jquery/blob/e8825a529b97a27b8b2e40eaaa7773189642c772/build/release/dist.js#L67) which doesn't preserve the directory structure, making the `sizzle` directory appear without the necessary `external` directory wrapper.

Reopening & marking as a blocker.

**Comment by mgol** [comment]
It'd be good to have a way of testing if the final structure is OK.

**Comment by timmywil** [comment]
I thought it was working, but maybe my local copy was wrong. It's tough to make an automated test because it's going through jquery-release. But, once it's working, we shouldn't have to touch it again.

**Comment by fleea** [comment]
Same problem here:

`Module not found: Error: Cannot resolve 'file' or 'directory' ../external/sizzle/dist/sizzle`

**Comment by yoga1290** [comment]
The latest uncompressed jQuery worked here with Webpack after adding `window.jQuery = window.$ = jQuery;` just before the last `return` line

**Comment by jvreeken** [comment]
same problem here, ERROR in ./~/jquery/src/selector-sizzle.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../external/sizzle/dist/sizzle

**Comment by timmywil** [comment]
We will have a fix in the next patch. Please use GitHub's reaction feature on the original post if you're having the same issue.
