### ISSUE TITLE
Edge 16 fails "css" test

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery#3866]
Before (last passing TestSwarm job for jquery/jquery)

* http://swarm.jquery.org/job/6254
* 90bac40a51 (25 Sep 2017)
* `Edge/15.15063`

After (first failing TestSwarm job, also first job that runs for Edge 16)

* http://swarm.jquery.org/job/6325
* 56e891dea1 (18 Oct 2017) 
* Ran for `Edge/16.16299`

* Edge 16 / css (1 failure) – <http://swarm.jquery.org/result/2477837>

<img width="928" alt="screen shot 2017-11-28 at 10 47 24" src="https://user-images.githubusercontent.com/156867/33337983-8ad9c4c2-d429-11e7-977d-1bfe0b31f920.png">

**Comment by Krinkle** [comment]
The Safari 11 support test failures are fixed by 50e3395e7e25d3286ed3daa17ee5ae4d862b0602.

**Comment by mgol** [comment]
Hmm, my mail claims this ticket refered to Safari 11 as well (which also still fails the tests, core ones to be precise: http://swarm.jquery.org/job/6499). That can be moved to a separate issue, though.

**Comment by Krinkle** [comment]
@mgol Yeah, I edited the ticket after creation. The ticket previously mentioned the "support" test failing in Safari 11 after we started testing there, but you already fixed that.
